import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";

import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";
import MixesProvider from "@/contexts/mixesContext";

import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getMixes = async (): Promise<Array<IMix> | Array<String>> => {
  try {
    const res = await fetch(
      `https://api.mixcloud.com/homesessionz/favorites/`,
      {
        cache: "force-cache",
      }
    );
    const { data: mixes } = await res.json();

    return mixes;
  } catch (error) {
    return [];
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mixes: IMix[] = await getMixes();

  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <MixesProvider>
          <Header mixes={mixes} />
          {children}
          <Footer />
        </MixesProvider>
      </body>
    </html>
  );
}
